### ISSUE TITLE
I'm encountering a `TypeError` when attempting to run the `qwak configure` command. 

### ISSUE THREAD

**Issue by Ajay263** [qwak-ai/qwak-examples#79]
This error occurs when executing the `qwak configure` command.

Environment Details:
- Operating System: Ubuntu 20.04 LTS
- Python Version: 3.10.14
- qwak Version: 0.5.74

```
Traceback (most recent call last):
  File "/home/Ajay/.local/bin/qwak", line 5, in <module>
    from qwak_sdk.main import qwak_cli
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/main.py", line 1, in <module>
    from qwak_sdk.cli import create_qwak_cli
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/cli.py", line 16, in <module>
    from qwak_sdk.commands.models.models_command_group import models_command_group
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/commands/models/models_command_group.py", line 7, in <module>
    from .build.ui import models_build
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/commands/models/build/ui.py", line 15, in <module>
    from qwak_sdk.commands.models.build._logic.build_steps import create_pipeline
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/commands/models/build/_logic/build_steps.py", line 11, in <module>
    from .phase.c_deploy import get_deploy_steps
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/commands/models/build/_logic/phase/c_deploy/__init__.py", line 2, in <module>
    from .deploy_build import DeployBuildStep
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/commands/models/build/_logic/phase/c_deploy/deploy_build.py", line 14, in <module>
    from qwak_sdk.commands.models.deployments.deploy.realtime.ui import deploy_realtime
  File "/home/Ajay/.local/lib/python3.8/site-packages/qwak_sdk/commands/models/deployments/deploy/realtime/ui.py", line 181, in <module>
    def realtime(
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1601, in __init__
    raise TypeError('Got secondary option for non boolean flag.')
TypeError: Got secondary option for non boolean flag.

```

**Comment by guyeshet** [comment]
Hey @Ajay263 , did you install it via a fresh installation?
Could you try again using a conda environment mabye?
